USE [JB Training]

SELECT TOP (1000) [Job]
      ,[Customer]
      ,[Name]
      ,[Top_Lvl_Job]
      ,[Status]
      ,[Expr1]
      ,[Open_Operations]
      ,[Work_Center]
      ,[WC_Vendor]
      ,[Description]
      ,[Est Operatiom Hours]
      ,[Est_Total_Hrs]
      ,[Sched_End]
      ,[Lead_Days]
      ,[Part_Number]
      ,[Expr3]
      ,[Priority]
      ,[Promised_Date]
      ,[Expr4]
      ,[DeliveryKey]
      ,[Sched_Start]
      ,[Expr5]
      ,[Expr2]
      ,[Expr6]
      ,[Master R]
      ,[Project L]
      ,[Repeat]
      ,[Packaging R]
      ,[FAI_Report]

INTO FAI
FROM [FAI_Report]


